services:
  - type: web
    name: hr-employee-system
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m nltk.downloader punkt wordnet
    startCommand: gunicorn app:app
    envVars:
      - key: HRMATE_EMAIL
        sync: false
      - key: HRMATE_APP_PASSWORD
        sync: false
